/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc2022.java19;

import java.util.List;

import aoc2022.java19.puzzles.Example;
import aoc2022.java19.puzzles.Puzzle;
import aoc2022.java19.puzzles.Puzzle1;

public class App {
    /* Very cool banner */
    private static final String BANNER = """
            AOC 2022 Java edition
            * *       * * *** *
             *       *         **
                 *     *     *
            *        ** *
                * **
              *              *
                           *
                       *  *     *
             *                 *


                            * *

                    """;



    public static void main(String[] args) {
        System.out.println(BANNER); // Print cool banner

        try {
            /* List puzzles here with dedicated inputs */
            List<Puzzle> puzzles = List.of(new Puzzle1(InputReader.read("1.txt")));

            /* Produce outputs for each puzzle */
            puzzles.stream().map(Puzzle::produceOutputs).forEach(System.out::println);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
